name: Build signed test apk

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode and Write Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | openssl base64 -d -out my-release-key.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Verify Keystore File
        run: |
          if [ -s my-release-key.jks ]; then
          echo "Keystore file created successfully."
          ls -l my-release-key.jks
          else
          echo "Keystore file is empty or missing!" && exit 1
          fi

      - name: Debug Environment Variables
        run: |
          echo "KEYSTORE_PASSWORD is set" 
          echo "KEY_ALIAS is set"
          echo "KEY_PASSWORD is set"
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Check Keystore File Existence
        run: ls -l ./my-release-key.jks

      - name: Check Keystore Path
        run: realpath ./my-release-key.jks

      - name: Build the project
        run: ./gradlew assembleRelease --no-daemon
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: signed-test-apk
          path: app/build/outputs/apk/release/*.apk