name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode and Write Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | openssl base64 -d -out my-release-key.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Verify Keystore File
        run: |
          if [ -s my-release-key.jks ]; then
          echo "Keystore file created successfully."
          ls -l my-release-key.jks
          else
          echo "Keystore file is empty or missing!" && exit 1
          fi

      - name: Debug Environment Variables
        run: |
          echo "KEYSTORE_PASSWORD is set" 
          echo "KEY_ALIAS is set"
          echo "KEY_PASSWORD is set"
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Move Keystore File
        run: |
          mv ./my-release-key.jks ./app/my-release-key.jks

      - name: Check Keystore File Existence
        run: ls -l ./my-release-key.jks

      - name: Check Keystore Path
        run: realpath ./my-release-key.jks

      - name: Build the project
        run: ./gradlew assembleRelease --no-daemon
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play-action@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: "com.example.wordle"  # Replace with your actual package name
          appApk: "app/build/outputs/bundle/release/app-release.aab"  # Path to your .aab file
          track: "production"  # Track can be 'internal', 'beta', or 'production'
